### ISSUE TITLE
Trivial doc request re SQLite support for JSON

### ISSUE THREAD

**Issue by chrisinmtown** [edelooff/sqlalchemy-json#32]
Thanks for this package. I just want to ask if it might be appropriate to update this README.rst text:
```
.. your database does not natively support JSON (e.g. SQLite),
or you wish to serialize to a format other than JSON,
you'll need to provide a different backing type.
```
I believe - but please correct me if I got this wrong - that SQLite supports JSON natively since version 3.9. The current version in Python 3.9 is 3.36.

Hope this helps.

**Comment by jeanmonet** [comment]
Certainly the case - I'm currently working with JSON fields in SQLite.

FYI: https://dba.stackexchange.com/questions/122198/is-it-possible-to-store-and-query-json-in-sqlite

> SQLite 3.9 introduced a new extension ([JSON1](https://www.sqlite.org/json1.html)) that allows you to easily work with JSON data .
> Also, it introduced support for indexes on expressions, which (in my understanding) should allow you to define indexes on your JSON data as well.

**Comment by edelooff** [comment]
Updated in #34
