### ISSUE TITLE
please create/push tags for new releases

### ISSUE THREAD

**Issue by FelixSchwarz** [edelooff/sqlalchemy-json#39]
It would be nice if each pypi release had an according git tag so it is easier to see which changes went into a specific release.

For example I'm using this quite often to determine the lowest suitable version of my dependencies.

**Comment by edelooff** [comment]
Thanks for the suggestion, that's pretty useful. Added this for the current v0.6.0 and the previous v0.5.0.

**Comment by FelixSchwarz** [comment]
Thank you for your work on this library, very much appreciated.
