### ISSUE TITLE
setup.py claims support for Python 2 but code actually requires Python 3

### ISSUE THREAD

**Issue by FelixSchwarz** [edelooff/sqlalchemy-json#40]
Your [setup.py](https://github.com/edelooff/sqlalchemy-json/blob/c52b2fc3f4a8cb20b2a692e4ae94575fa849c251/setup.py#L31) claims Python 2 support but `TrackedList.sort()` uses a [keyword-only parameter](https://github.com/edelooff/sqlalchemy-json/blob/ccac751ccf01d3404d655576997caac16685c3a8/sqlalchemy_json/track.py#L183) which is only valid for Python 3.

Probably Python 2 support is a non-goal by now so I suggest:

- fix `setup.py`
- add `python_requires = ">= 3.6"

If you like I can create a pull request to fix this issue.

**Comment by edelooff** [comment]
That's a good point, and yes, Python 2 compatibility is no longer a goal. Happy to accept the PR.
