### ISSUE TITLE
impl = sqlalchemy.String requires length for MySQL

### ISSUE THREAD

**Issue by penguinolog** [edelooff/sqlalchemy-json#6]
`impl = sqlalchemy.String` requires length for MySQL
Replace by `impl = sqlalchemy.LargeBinary` fixes this due to possibility of handling BLOB without size.

**Comment by penguinolog** [comment]
#7 fixing this

**Comment by edelooff** [comment]
This should be fixed with the merge of #8 which uses the `JSONType` provided by SQLAlchemy-utils.
